# common
PROJECT = "Project"
VERSION = "Version"
DATE = "Date"
T_MODULE = "T_Module"
T_LINE = "T_Line"
T_CC = "T_CC"
TASK = "Task"
TASK_LIST = ["BUG", "DOCS", "REFACTOR", "TESTING", "FEATURE", "UPGRADE", "RELEASE", "SUPPORT", "OTHER"]
PROJECT_LIST = [
  "angular/angular"
  ,"nodejs/node"
  ,"openstack/neutron"
  ,"vuejs/vue"
  ,"home-assistant/home-assistant"
  ,"tensorflow/tensorflow"
  ,"moby/moby"
  ,"gitlabhq/gitlabhq"
  ,"dotnet/orleans"
  ,"dotnet/roslyn"
  ,"ansible/ansible"
  ,"cloudfoundry/cli"
  ,"openstack/nova"
  ,"angular/angular.js"
  ,"auth0/lock"
  ,"kubernetes/kubernetes"
  ,"apache/mesos"
  ,"odin-lang/Odin"
  ,"NixOS/nixpkgs"
  ,"facebook/react"
  ,"Homebrew/brew"
  ,"openstack/cinder"
  ,"elastic/elasticsearch"
  ,"torvalds/linux"
  ,"cloudfoundry/cf-deployment"
  ,"OfficeDev/office-js"
]
OTHER_PROJECT_LIST = [
  "d3/d3"
    ,"socketio/socket.io"
    ,"webpack/webpack"
    ,"jekyll/jekyll"
    ,"kennethreitz/requests"
    ,"lodash/lodash"
    ,"typicode/json-server"
    ,"Unitech/pm2"
    ,"videojs/video.js"
    ,"plataformatec/devise"
    ,"facebook/jest"
    ,"webtorrent/webtorrent"
    ,"npm/npm"
    ,"Automattic/mongoose"
    ,"visionmedia/superagent"
    ,"keystonejs/keystone"
    ,"yabwe/medium-editor"
    ,"jgm/pandoc"
    ,"swagger-api/swagger-ui"
    ,"SeleniumHQ/selenium"
    ,"BrowserSync/browser-sync"
    ,"jhipster/generator-jhipster"
    ,"karma-runner/karma"
    ,"jsdom/jsdom"
    ,"stylus/stylus"
    ,"NetEase/pomelo"
    ,"systemjs/systemjs"
    ,"jordansissel/fpm"
    ,"nightwatchjs/nightwatch"
    ,"danialfarid/ng-file-upload"
    ,"NaturalNode/natural"
    ,"datproject/dat"
    ,"middleman/middleman"
    ,"fluent/fluentd"
    ,"zloirock/core-js"
    ,"vega/vega"
    ,"josdejong/mathjs"
    ,"AutoMapper/AutoMapper"
]

T_RECORDS = "T_Records"
NT = "NT"
NO = "NO"
LINE = "Line"
MODULE = "Module"
T_CONTRIBUTORS = "T_Contributors"

# core contributor
NT_CC = "NT_CC"
NO_CC = "NO_CC"
MODULE_CC = "Module_CC"
LINE_CC = "Line_CC"
T_CC = "T_CC"

# external contributor
NT_EC = "NT_EC"
NO_EC = "NO_EC"
MODULE_EC = "Module_EC"
LINE_EC = "Line_EC"
T_EC = "T_EC"

# data analysis dynamic columns
OBSERVED = "Observed"
PREDICTED = "Predicted"
DIFFERENCE = "Difference"
PERCENT_ERROR = "Percent Error"

# results output columns
MODEL = "Model"
R_SQUARED = "R_Squared"
R_SQUARED_ADJ = "R_Squared_Adj"
MAE = "MAE"
MSE = "MSE"
RMSE = "RMSE"
PRED_25 = "PRED_25"
PRED_50 = "PRED_50"
